# Generated by Django 3.2.3 on 2021-05-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20210514_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
